plugins {
	id 'net.fabricmc.fabric-loom' version '1.16.+'
	id 'maven-publish'
}


base {
  archivesName = project.archives_base_name
}
version = project.mod_version
group = project.maven_group

repositories {
	maven { url = "https://maven.nucleoid.xyz/" }
	maven { url = "https://maven.gegy.dev/" }
	maven { url = "https://api.modrinth.com/maven" }
	maven { url = "https://repo.viaversion.com" }
}

loom {
  accessWidenerPath = file("src/main/resources/extras.accesswidener")
}

fabricApi {
	configureDataGeneration {
		createSourceSet = true
		modId = "nucleoid_extras"
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	testImplementation "net.fabricmc:fabric-loader-junit:${project.loader_version}"

	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

	implementation "xyz.nucleoid:plasmid:${project.plasmid_version}"
	implementation "eu.pb4:factorytools:${project.factorytools_version}"
  runtimeOnly "eu.pb4:polymer-autohost:${project.polymer_version}"


	//compileOnly "com.viaversion:viaversion-api:4.7.0-SNAPSHOT"
	compileOnly "dev.gegy:player-roles-api:${project.player_roles_version}"
}

test {
	useJUnitPlatform()
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": project.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.encoding = "UTF-8"
	it.options.release = 25
}

java {
	withSourcesJar()
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.archives_base_name}"}
	}
}
