# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
minecraft_version=1.21.8
yarn_mappings=1.21.8+build.1
loader_version=0.16.14

# Dependencies
fabric_version=0.131.0+1.21.8
plasmid_version=0.6.6-SNAPSHOT+1.21.7
player_roles_version=1.6.14
factorytools_version=0.7.1+1.21.6
polymer_version=0.13.9+1.21.8

# Mod Properties
mod_version=1.3.3
maven_group=xyz.nucleoid
archives_base_name=nucleoid-extras
