# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
minecraft_version=1.21.7
yarn_mappings=1.21.7+build.4
loader_version=0.16.14

# Dependencies
fabric_version=0.128.2+1.21.7
plasmid_version=0.6.6-SNAPSHOT+1.21.7
player_roles_version=1.6.14
factorytools_version=0.7.1+1.21.6

# Mod Properties
mod_version=1.3.3
maven_group=xyz.nucleoid
archives_base_name=nucleoid-extras
